# -*- coding: utf-8 -*-
"""amansanwalweek1project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sIgHgoZc8e0kLf-vb7UT6TaWuSp9SY5K
"""

import pandas as pd

# STEP1&2)downloaded the csv file and in next step reading the csv file using pandas data frame

df=pd.read_csv('IPL 2022 Batters.csv')
df

#step 3) to check any null value first we check for na values if any which is not the case , hence now we check for - values that may be in the table , searching
# for - in each column seperately

df.isnull().sum()

df[df['Mat']=='-']

df[df['Inns']=='-']

df[df['NO']=='-']

df[df['Runs']=='-']

df[df['HS']=='-']

df[df['Avg']=='-']

#we find that - are present in the Avg column

df[df['BF']=='-']

df[df['SR']=='-']

df[df['100']=='-']

df[df['50']=='-']

df[df['4s']=='-']

#to remove these - values , we remove the rows in which these are present

df.drop([118,124,127,145,150,157,160,161],axis=0,inplace=True)

df

#step 4 - to plot the graphs of line graph and scatter plot

import numpy as np
from matplotlib import pyplot as plt

x=df['4s'].to_numpy()
y=df['Runs'].to_numpy()

#writing code to plot the line graph

plt.plot(x,y,color="orange")
plt.title("4s vs total runs")
plt.xlabel("4s")
plt.ylabel("total runs")
plt.grid(True)
plt.show()

#writing code for plotting the scatter plot

plt.scatter(x,y,color="red",s=5)
plt.title("4s vs total runs")
plt.xlabel("4s")
plt.ylabel("total runs")
plt.grid(True)
plt.show()

#step 5 - to perform linear regression with the 4s as independent variable and Runs as the dependent variable

from sklearn import linear_model

reg=linear_model.LinearRegression()
reg.fit(df[['4s']],df.Runs)

#trying to predict the Total runs scored when the 4s scored are equal to 26

reg.predict([[26]])

#step 6) creating two data frames , one for Total runs which act as feature and another for 4s scored which acts as target

a=df['4s']
b=df['Runs']

a

b

#Step 7) Now we split the dataset created in the previous steps using train_test_split utility from sklearn into training and testing with the 4s scored as target

from sklearn.model_selection import train_test_split
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2)

a_train

b_train

a_test

b_test

#step 8) now using linear regression with a_train as dependent variable and b_train as independent variable

rege=linear_model.LinearRegression()
rege.fit([a_train],[b_train])

#please note that i am facing a problem while predicting the values for a_test. please tell how to resolve this issue. also note since i am unablke to complete this step i am unable
# proceed to step 9

rege.predict([a_test])